using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using DevCompanion.Agent.Services.Notification;

namespace DevCompanion.Agent.Services.Analyzer;

public class ApiScanner
{
    private readonly HttpClient _httpClient;
    private readonly ILlmService _llmService;
    private readonly ReportGenerator _reportGenerator;
    private readonly WhatsAppService _whatsAppService;
    private readonly TelegramService _telegramService;
    private readonly ILogger<ApiScanner> _logger;

    public ApiScanner(
        HttpClient httpClient,
        ILlmService llmService,
        ReportGenerator reportGenerator,
        WhatsAppService whatsAppService,
        TelegramService telegramService,
        ILogger<ApiScanner> logger)
    {
        _httpClient = httpClient;
        _llmService = llmService;
        _reportGenerator = reportGenerator;
        _whatsAppService = whatsAppService;
        _telegramService = telegramService;
        _logger = logger;
    }

    public async Task ScanProjectApiAsync(string projectRoot, string baseUrl, string swaggerPath)
    {
        try
        {
            var swaggerUrl = $"{baseUrl.TrimEnd('/')}{swaggerPath}";
            _logger.LogInformation("Fetching Swagger JSON from {Url}...", swaggerUrl);

            var response = await _httpClient.GetAsync(swaggerUrl);
            if (!response.IsSuccessStatusCode)
            {
                _logger.LogWarning("Failed to fetch Swagger JSON. Status: {Status}", response.StatusCode);
                return;
            }

            var swaggerJson = await response.Content.ReadAsStringAsync();
            var apiMetadata = ExtractApiMetadata(swaggerJson);
            if (string.IsNullOrEmpty(apiMetadata))
            {
                _logger.LogWarning("Could not parse paths from Swagger JSON.");
                return;
            }

            _logger.LogInformation("Generating test cases using LLM for endpoints: {Metadata}", apiMetadata);
            var testCasesJson = await GenerateTestCasesAsync(apiMetadata);
            var testCases = ParseTestCases(testCasesJson);

            if (testCases == null || testCases.Count == 0)
            {
                _logger.LogInformation("No test cases generated by LLM.");
                return;
            }

            _logger.LogInformation("Executing {Count} test cases silently against local host API...", testCases.Count);
            await RunTestCasesAsync(projectRoot, baseUrl, testCases);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error occurred during API shadow testing.");
        }
    }

    private string ExtractApiMetadata(string swaggerJson)
    {
        try
        {
            using var doc = JsonDocument.Parse(swaggerJson);
            if (!doc.RootElement.TryGetProperty("paths", out var paths))
            {
                return string.Empty;
            }

            var endpoints = new List<object>();

            foreach (var pathProperty in paths.EnumerateObject())
            {
                var path = pathProperty.Name;
                foreach (var methodProperty in pathProperty.Value.EnumerateObject())
                {
                    var method = methodProperty.Name;
                    var parametersList = new List<string>();

                    if (methodProperty.Value.TryGetProperty("parameters", out var parameters))
                    {
                        foreach (var parameter in parameters.EnumerateArray())
                        {
                            if (parameter.TryGetProperty("name", out var name) && 
                                parameter.TryGetProperty("in", out var @in))
                            {
                                parametersList.Add($"{name.GetString()} (in {@in.GetString()})");
                            }
                        }
                    }

                    var hasRequestBody = methodProperty.Value.TryGetProperty("requestBody", out _);

                    endpoints.Add(new
                    {
                        Path = path,
                        Method = method.ToUpper(),
                        Parameters = parametersList,
                        HasRequestBody = hasRequestBody
                    });
                }
            }

            return JsonSerializer.Serialize(endpoints);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to parse Swagger JSON structure.");
            return string.Empty;
        }
    }

    private async Task<string> GenerateTestCasesAsync(string apiMetadata)
    {
        var systemPrompt = @"You are a QA automation and penetration testing assistant. 
Your task is to generate a list of fuzz/boundary testing payloads based on API route schemas.
Generate edge cases (empty strings, huge numbers, type mismatches) and common C# vulnerabilities (such as SQL injection patterns like ' OR 1=1 --, directory traversal, etc.).

Respond ONLY with a valid JSON array of test cases. Do not include markdown code block formatting. Format:
[
  {
    ""route"": ""/api/v1/products/123"",
    ""method"": ""GET"",
    ""body"": null,
    ""description"": ""Testing normal integer path parameter""
  },
  {
    ""route"": ""/api/v1/products/null"",
    ""method"": ""GET"",
    ""body"": null,
    ""description"": ""Testing type mismatch on integer parameter""
  }
]";

        var userPrompt = $"Endpoints metadata:\n{apiMetadata}\n\nGenerate up to 8 diverse test cases (focusing on edge cases, SQLi, boundary checks). Return ONLY the raw JSON array.";
        var response = await _llmService.ChatAsync(systemPrompt, userPrompt);
        
        // Strip markdown backticks if LLM included them
        if (response.StartsWith("```"))
        {
            var lines = response.Split('\n');
            var cleanText = new StringBuilder();
            foreach (var line in lines)
            {
                if (!line.Trim().StartsWith("```"))
                {
                    cleanText.AppendLine(line);
                }
            }
            response = cleanText.ToString();
        }

        return response.Trim();
    }

    private List<ApiTestCase>? ParseTestCases(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<List<ApiTestCase>>(json, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to deserialize test cases. Raw response was: {Raw}", json);
            return null;
        }
    }

    private async Task RunTestCasesAsync(string projectRoot, string baseUrl, List<ApiTestCase> testCases)
    {
        var semaphore = new SemaphoreSlim(3); // Control concurrency to prevent overloading the local dev server
        var tasks = testCases.Select(async testCase =>
        {
            await semaphore.WaitAsync();
            try
            {
                var fullUrl = $"{baseUrl.TrimEnd('/')}{testCase.Route}";
                var request = new HttpRequestMessage(new HttpMethod(testCase.Method), fullUrl);

                if (testCase.Body != null)
                {
                    var bodyString = testCase.Body is JsonElement element ? element.GetRawText() : JsonSerializer.Serialize(testCase.Body);
                    request.Content = new StringContent(bodyString, Encoding.UTF8, "application/json");
                }

                _logger.LogInformation("Testing Endpoint: {Method} {Route} ({Desc})", testCase.Method, testCase.Route, testCase.Description);
                var response = await _httpClient.SendAsync(request);

                if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError) // 500
                {
                    var responseBody = await response.Content.ReadAsStringAsync();
                    _logger.LogWarning("ENDPOINT FAILED (500 Error): {Method} {Route}", testCase.Method, testCase.Route);
                    await AnalyzeFailedEndpointAsync(projectRoot, testCase, responseBody);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to run test case: {Method} {Route}", testCase.Method, testCase.Route);
            }
            finally
            {
                semaphore.Release();
            }
        });

        await Task.WhenAll(tasks);
    }

    private async Task AnalyzeFailedEndpointAsync(string projectRoot, ApiTestCase testCase, string responseBody)
    {
        var systemPrompt = @"You are an expert .NET AppSec (Application Security) Engineer and Principal Cyber Security Architect.
Your task is to analyze the provided security vulnerability or crash report for an ASP.NET Core application built on .NET 10 following Clean Architecture and Domain-Driven Design (DDD) principles.

Provide a comprehensive, production-ready security remediation strategy covering:
1. Threat & Vulnerability Analysis: Identify the exact nature of the vulnerability (e.g., OWASP Top 10, BOLA, SQL Injection, Mass Assignment, CSRF, or SSRF). Explain the potential exploit scenario and its technical impact on the system.
2. Blast Radius & Context Assessment: Map out the affected components across the architecture layers. Determine if the vulnerability stems from Presentation, Application, Infrastructure, or NuGet packages.
3. Secure Remediation (The Professional Fix): Provide the exact, refactored C# / .NET 10 code to eliminate the vulnerability. The solution MUST adhere to Clean Code practices, utilizing modern secure-by-default features of .NET 10, and must NOT break existing business contracts or layer isolation.
4. Architectural Hardening & Verification: Detail how to structurally prevent similar vulnerabilities in the future. Explain how to write a secure automated integration test to verify the fix and prevent future regressions.";

        var userPrompt = $@"Failed Endpoint: {testCase.Method} {testCase.Route}
Payload / Body: {testCase.Body}
Vulnerability/Case Description: {testCase.Description}
Server Response (500 Content):
{responseBody}

Generate the fix. Write the code in a standard markdown code block.";

        _logger.LogInformation("Analyzing shadow test failure with LLM...");
        var response = await _llmService.ChatAsync(systemPrompt, userPrompt);

        // Write report
        await _reportGenerator.GenerateVulnerabilityReportAsync(
            projectRoot,
            testCase.Route,
            testCase.Body?.ToString() ?? "None",
            "500 Internal Server Error",
            testCase.Description,
            response);

        // Send WhatsApp & Telegram alerts
        var alertMessage = $"⚠️ *DevCompanion API Vulnerability Alert!*\n" +
                            $"Project: {Path.GetFileName(projectRoot)}\n" +
                            $"Failed Endpoint: {testCase.Method} {testCase.Route}\n" +
                            $"Trigger Payload: {testCase.Description}\n\n" +
                            $"🔍 Check *AI_Vulnerability_Report.md* in your project for the proposed Clean Architecture fix.";
        await Task.WhenAll(
            _whatsAppService.SendNotificationAsync(alertMessage),
            _telegramService.SendNotificationAsync(alertMessage)
        );
    }

    private class ApiTestCase
    {
        public string Route { get; set; } = string.Empty;
        public string Method { get; set; } = "GET";
        public object? Body { get; set; }
        public string Description { get; set; } = string.Empty;
    }
}
